/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardCodeRouteImport } from './routes/board.$code'
import { Route as DraftCodeRouteImport } from './routes/draft.$code'
import { Route as HistoryCodeRouteImport } from './routes/history.$code'
import { Route as RecapCodeRouteImport } from './routes/recap.$code'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardCodeRoute = BoardCodeRouteImport.update({
  id: '/board/$code',
  path: '/board/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftCodeRoute = DraftCodeRouteImport.update({
  id: '/draft/$code',
  path: '/draft/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCodeRoute = HistoryCodeRouteImport.update({
  id: '/history/$code',
  path: '/history/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapCodeRoute = RecapCodeRouteImport.update({
  id: '/recap/$code',
  path: '/recap/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board/$code': typeof BoardCodeRoute
  '/draft/$code': typeof DraftCodeRoute
  '/history/$code': typeof HistoryCodeRoute
  '/recap/$code': typeof RecapCodeRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/$code': typeof BoardCodeRoute
  '/draft/$code': typeof DraftCodeRoute
  '/history/$code': typeof HistoryCodeRoute
  '/recap/$code': typeof RecapCodeRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board/$code': typeof BoardCodeRoute
  '/draft/$code': typeof DraftCodeRoute
  '/history/$code': typeof HistoryCodeRoute
  '/recap/$code': typeof RecapCodeRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board/$code'
    | '/draft/$code'
    | '/history/$code'
    | '/recap/$code'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board/$code'
    | '/draft/$code'
    | '/history/$code'
    | '/recap/$code'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/board/$code'
    | '/draft/$code'
    | '/history/$code'
    | '/recap/$code'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardCodeRoute: typeof BoardCodeRoute
  DraftCodeRoute: typeof DraftCodeRoute
  HistoryCodeRoute: typeof HistoryCodeRoute
  RecapCodeRoute: typeof RecapCodeRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$code': {
      id: '/board/$code'
      path: '/board/$code'
      fullPath: '/board/$code'
      preLoaderRoute: typeof BoardCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$code': {
      id: '/draft/$code'
      path: '/draft/$code'
      fullPath: '/draft/$code'
      preLoaderRoute: typeof DraftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$code': {
      id: '/history/$code'
      path: '/history/$code'
      fullPath: '/history/$code'
      preLoaderRoute: typeof HistoryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$code': {
      id: '/recap/$code'
      path: '/recap/$code'
      fullPath: '/recap/$code'
      preLoaderRoute: typeof RecapCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardCodeRoute: BoardCodeRoute,
  DraftCodeRoute: DraftCodeRoute,
  HistoryCodeRoute: HistoryCodeRoute,
  RecapCodeRoute: RecapCodeRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
