INSERT INTO public.players (name, position, nfl_team, bye_week, rank, adp, stat_line)
SELECT name, pos, team, bye, rn::int, rn::numeric, stat
FROM (
  SELECT v.*, row_number() OVER () AS rn
  FROM (VALUES
    ('Ja''Marr Chase','WR','CIN',10,'1,708 yds, 17 TD'),
    ('Justin Jefferson','WR','MIN',6,'1,533 yds, 10 TD'),
    ('Bijan Robinson','RB','ATL',5,'1,456 scrim yds, 15 TD'),
    ('Saquon Barkley','RB','PHI',9,'2,005 rush yds, 13 TD'),
    ('CeeDee Lamb','WR','DAL',10,'1,194 yds, 6 TD'),
    ('Jahmyr Gibbs','RB','DET',8,'1,929 scrim yds, 20 TD'),
    ('Puka Nacua','WR','LAR',8,'990 yds, 3 TD'),
    ('Malik Nabers','WR','NYG',14,'1,204 yds, 7 TD'),
    ('Amon-Ra St. Brown','WR','DET',8,'1,263 yds, 12 TD'),
    ('Christian McCaffrey','RB','SF',14,'injury-shortened season'),
    ('Nico Collins','WR','HOU',6,'1,006 yds, 7 TD'),
    ('Brian Thomas Jr.','WR','JAX',8,'1,282 yds, 10 TD'),
    ('Ashton Jeanty','RB','LV',8,'rookie, Boise State standout'),
    ('De''Von Achane','RB','MIA',12,'1,499 scrim yds, 11 TD'),
    ('Drake London','WR','ATL',5,'1,271 yds, 9 TD'),
    ('Brock Bowers','TE','LV',8,'1,194 yds, 5 TD'),
    ('A.J. Brown','WR','PHI',9,'1,079 yds, 7 TD'),
    ('Jonathan Taylor','RB','IND',11,'1,431 rush yds, 11 TD'),
    ('Derrick Henry','RB','BAL',7,'1,921 rush yds, 16 TD'),
    ('Josh Jacobs','RB','GB',5,'1,329 rush yds, 15 TD'),
    ('Tyreek Hill','WR','MIA',12,'959 yds, 6 TD'),
    ('Bucky Irving','RB','TB',9,'1,122 rush yds, 8 TD'),
    ('Trey McBride','TE','ARI',8,'1,146 yds, 2 TD'),
    ('Ladd McConkey','WR','LAC',12,'1,149 yds, 7 TD'),
    ('Garrett Wilson','WR','NYJ',9,'1,104 yds, 7 TD'),
    ('Chase Brown','RB','CIN',10,'990 rush yds, 7 TD'),
    ('Kyren Williams','RB','LAR',8,'1,299 rush yds, 14 TD'),
    ('Marvin Harrison Jr.','WR','ARI',8,'885 yds, 8 TD'),
    ('Tee Higgins','WR','CIN',10,'911 yds, 10 TD'),
    ('Davante Adams','WR','LAR',8,'1,063 yds, 8 TD'),
    ('Terry McLaurin','WR','WAS',12,'1,096 yds, 13 TD'),
    ('George Kittle','TE','SF',14,'1,106 yds, 8 TD'),
    ('Lamar Jackson','QB','BAL',7,'4,172 pass yds, 41 TD'),
    ('Josh Allen','QB','BUF',7,'3,731 pass yds, 28 TD, 12 rush TD'),
    ('Jayden Daniels','QB','WAS',12,'3,568 pass yds, 891 rush yds'),
    ('Jalen Hurts','QB','PHI',9,'2,903 pass yds, 14 rush TD'),
    ('Joe Burrow','QB','CIN',10,'4,918 pass yds, 43 TD'),
    ('Breece Hall','RB','NYJ',9,'1,359 scrim yds, 8 TD'),
    ('James Cook','RB','BUF',7,'1,267 scrim yds, 18 TD'),
    ('Alvin Kamara','RB','NO',11,'1,493 scrim yds, 8 TD'),
    ('DK Metcalf','WR','PIT',5,'992 yds, 5 TD'),
    ('DJ Moore','WR','CHI',5,'966 yds, 6 TD'),
    ('Jaxon Smith-Njigba','WR','SEA',8,'1,130 yds, 6 TD'),
    ('Mike Evans','WR','TB',9,'1,004 yds, 11 TD'),
    ('Courtland Sutton','WR','DEN',12,'1,081 yds, 8 TD'),
    ('Zay Flowers','WR','BAL',7,'1,059 yds, 4 TD'),
    ('Rome Odunze','WR','CHI',5,'734 yds, 3 TD'),
    ('Xavier Worthy','WR','KC',6,'638 yds, 6 TD'),
    ('Jameson Williams','WR','DET',8,'1,001 yds, 7 TD'),
    ('Sam LaPorta','TE','DET',8,'726 yds, 7 TD'),
    ('Travis Kelce','TE','KC',6,'823 yds, 3 TD'),
    ('Mark Andrews','TE','BAL',7,'673 yds, 11 TD'),
    ('T.J. Hockenson','TE','MIN',6,'455 yds, 1 TD'),
    ('David Njoku','TE','CLE',9,'505 yds, 5 TD'),
    ('Patrick Mahomes','QB','KC',6,'3,928 pass yds, 26 TD'),
    ('Baker Mayfield','QB','TB',9,'4,500 pass yds, 41 TD'),
    ('Bo Nix','QB','DEN',12,'3,775 pass yds, 29 TD'),
    ('Kyler Murray','QB','ARI',8,'3,851 pass yds, 21 TD'),
    ('Justin Herbert','QB','LAC',12,'3,870 pass yds, 23 TD'),
    ('Brock Purdy','QB','SF',14,'3,864 pass yds, 20 TD'),
    ('C.J. Stroud','QB','HOU',6,'3,727 pass yds, 20 TD'),
    ('Caleb Williams','QB','CHI',5,'3,541 pass yds, 20 TD'),
    ('Dak Prescott','QB','DAL',10,'1,978 pass yds in 8 games'),
    ('Jared Goff','QB','DET',8,'4,629 pass yds, 37 TD'),
    ('Tua Tagovailoa','QB','MIA',12,'2,867 pass yds, 19 TD'),
    ('Drake Maye','QB','NE',14,'2,276 pass yds, 15 TD'),
    ('Kenneth Walker III','RB','SEA',8,'573 rush yds, 7 TD'),
    ('Omarion Hampton','RB','LAC',12,'rookie, North Carolina'),
    ('TreVeyon Henderson','RB','NE',14,'rookie, Ohio State'),
    ('Quinshon Judkins','RB','CLE',9,'rookie, Ohio State'),
    ('RJ Harvey','RB','DEN',12,'rookie, UCF'),
    ('Kaleb Johnson','RB','PIT',5,'rookie, Iowa'),
    ('Isiah Pacheco','RB','KC',6,'310 rush yds in 7 games'),
    ('Aaron Jones','RB','MIN',6,'1,138 rush yds, 5 TD'),
    ('David Montgomery','RB','DET',8,'775 rush yds, 12 TD'),
    ('Tony Pollard','RB','TEN',10,'1,079 rush yds, 5 TD'),
    ('Chuba Hubbard','RB','CAR',14,'1,195 rush yds, 10 TD'),
    ('Rhamondre Stevenson','RB','NE',14,'801 rush yds, 7 TD'),
    ('D''Andre Swift','RB','CHI',5,'959 rush yds, 6 TD'),
    ('Travis Etienne Jr.','RB','JAX',8,'558 rush yds, 2 TD'),
    ('Javonte Williams','RB','DAL',10,'513 rush yds, 4 TD'),
    ('Najee Harris','RB','LAC',12,'1,043 rush yds, 6 TD'),
    ('Brian Robinson Jr.','RB','WAS',12,'799 rush yds, 8 TD'),
    ('Zach Charbonnet','RB','SEA',8,'569 rush yds, 8 TD'),
    ('Tyrone Tracy Jr.','RB','NYG',14,'839 rush yds, 5 TD'),
    ('Jaylen Warren','RB','PIT',5,'511 rush yds, 1 TD'),
    ('Rachaad White','RB','TB',9,'613 rush yds, 3 TD'),
    ('Tyjae Spears','RB','TEN',10,'312 rush yds, 4 TD'),
    ('Jordan Mason','RB','MIN',6,'789 rush yds, 3 TD'),
    ('Austin Ekeler','RB','WAS',12,'367 scrim yds, 4 TD'),
    ('J.K. Dobbins','RB','DEN',12,'905 rush yds, 9 TD'),
    ('Nick Chubb','RB','HOU',6,'332 rush yds, 3 TD'),
    ('Jaylen Wright','RB','MIA',12,'249 rush yds, 1 TD'),
    ('Blake Corum','RB','LAR',8,'207 rush yds, 1 TD'),
    ('Ray Davis','RB','BUF',7,'442 rush yds, 3 TD'),
    ('Bhayshul Tuten','RB','JAX',8,'rookie, Virginia Tech'),
    ('Cam Skattebo','RB','NYG',14,'rookie, Arizona State'),
    ('Devin Neal','RB','NO',11,'rookie, Kansas'),
    ('Trevor Etienne','RB','CAR',14,'rookie, Georgia'),
    ('DeVonta Smith','WR','PHI',9,'833 yds, 8 TD'),
    ('Jaylen Waddle','WR','MIA',12,'744 yds, 2 TD'),
    ('Chris Godwin','WR','TB',9,'576 yds, 5 TD in 7 games'),
    ('Calvin Ridley','WR','TEN',10,'1,017 yds, 4 TD'),
    ('Jerry Jeudy','WR','CLE',9,'1,229 yds, 4 TD'),
    ('Jakobi Meyers','WR','LV',8,'1,027 yds, 4 TD'),
    ('Khalil Shakir','WR','BUF',7,'821 yds, 4 TD'),
    ('Deebo Samuel','WR','WAS',12,'806 yds, 3 TD'),
    ('Rashee Rice','WR','KC',6,'288 yds, 2 TD in 3 games'),
    ('Ricky Pearsall','WR','SF',14,'400 yds, 3 TD'),
    ('Keon Coleman','WR','BUF',7,'556 yds, 4 TD'),
    ('Jayden Reed','WR','GB',5,'857 yds, 6 TD'),
    ('Christian Watson','WR','GB',5,'620 yds, 2 TD'),
    ('Matthew Golden','WR','GB',5,'rookie, Texas'),
    ('Travis Hunter','WR','JAX',8,'rookie, Colorado'),
    ('Tetairoa McMillan','WR','CAR',14,'rookie, Arizona'),
    ('Luther Burden III','WR','CHI',5,'rookie, Missouri'),
    ('Emeka Egbuka','WR','TB',9,'rookie, Ohio State'),
    ('Jordan Addison','WR','MIN',6,'875 yds, 9 TD'),
    ('Stefon Diggs','WR','NE',14,'496 yds, 3 TD'),
    ('Cooper Kupp','WR','SEA',8,'710 yds, 6 TD'),
    ('George Pickens','WR','DAL',10,'900 yds, 3 TD'),
    ('Michael Pittman Jr.','WR','IND',11,'808 yds, 3 TD'),
    ('Josh Downs','WR','IND',11,'803 yds, 5 TD'),
    ('Darnell Mooney','WR','ATL',5,'992 yds, 5 TD'),
    ('Tank Dell','WR','HOU',6,'667 yds, 3 TD'),
    ('Rashid Shaheed','WR','NO',11,'349 yds, 2 TD'),
    ('Wan''Dale Robinson','WR','NYG',14,'699 yds, 3 TD'),
    ('Marvin Mims Jr.','WR','DEN',12,'503 yds, 6 TD'),
    ('Adam Thielen','WR','CAR',14,'615 yds, 5 TD'),
    ('Hollywood Brown','WR','KC',6,'150 yds, 1 TD'),
    ('Quentin Johnston','WR','LAC',12,'711 yds, 8 TD'),
    ('Dontayvion Wicks','WR','GB',5,'415 yds, 2 TD'),
    ('Romeo Doubs','WR','GB',5,'601 yds, 4 TD'),
    ('Alec Pierce','WR','IND',11,'824 yds, 7 TD'),
    ('Brandon Aiyuk','WR','SF',14,'374 yds, injury return'),
    ('Jauan Jennings','WR','SF',14,'975 yds, 6 TD'),
    ('Xavier Legette','WR','CAR',14,'497 yds, 4 TD'),
    ('Ja''Lynn Polk','WR','NE',14,'87 yds, 2 TD'),
    ('Kyle Williams','WR','NE',14,'rookie, Washington State'),
    ('Jack Bech','WR','LV',8,'rookie, TCU'),
    ('Tre Harris','WR','LAC',12,'rookie, Ole Miss'),
    ('Jalen Royals','WR','KC',6,'rookie, Utah State'),
    ('Isaac TeSlaa','WR','DET',8,'rookie, Arkansas'),
    ('Tucker Kraft','TE','GB',5,'707 yds, 7 TD'),
    ('Jonnu Smith','TE','PIT',5,'884 yds, 8 TD'),
    ('Evan Engram','TE','DEN',12,'365 yds, 1 TD'),
    ('Dalton Kincaid','TE','BUF',7,'448 yds, 2 TD'),
    ('Colston Loveland','TE','CHI',5,'rookie, Michigan'),
    ('Tyler Warren','TE','IND',11,'rookie, Penn State'),
    ('Isaiah Likely','TE','BAL',7,'477 yds, 6 TD'),
    ('Hunter Henry','TE','NE',14,'674 yds, 2 TD'),
    ('Cade Otton','TE','TB',9,'600 yds, 4 TD'),
    ('Pat Freiermuth','TE','PIT',5,'653 yds, 7 TD'),
    ('Kyle Pitts','TE','ATL',5,'602 yds, 4 TD'),
    ('Dallas Goedert','TE','PHI',9,'496 yds, 2 TD'),
    ('Zach Ertz','TE','WAS',12,'654 yds, 7 TD'),
    ('Chig Okonkwo','TE','TEN',10,'479 yds, 2 TD'),
    ('Mike Gesicki','TE','CIN',10,'665 yds, 2 TD'),
    ('Brenton Strange','TE','JAX',8,'411 yds, 2 TD'),
    ('Jake Ferguson','TE','DAL',10,'494 yds, 0 TD'),
    ('Noah Fant','TE','SEA',8,'500 yds, 1 TD'),
    ('Juwan Johnson','TE','NO',11,'548 yds, 2 TD'),
    ('Michael Mayer','TE','LV',8,'335 yds, 0 TD'),
    ('Jordan Love','QB','GB',5,'3,389 pass yds, 25 TD'),
    ('Trevor Lawrence','QB','JAX',8,'2,045 pass yds, 11 TD'),
    ('Geno Smith','QB','LV',8,'4,320 pass yds, 21 TD'),
    ('J.J. McCarthy','QB','MIN',6,'first full season'),
    ('Michael Penix Jr.','QB','ATL',5,'775 pass yds in 3 starts'),
    ('Matthew Stafford','QB','LAR',8,'3,762 pass yds, 20 TD'),
    ('Sam Darnold','QB','SEA',8,'4,319 pass yds, 35 TD'),
    ('Bryce Young','QB','CAR',14,'2,403 pass yds, 15 TD'),
    ('Anthony Richardson','QB','IND',11,'1,814 pass yds, 499 rush yds'),
    ('Cam Ward','QB','TEN',10,'rookie, Miami'),
    ('Aaron Rodgers','QB','PIT',5,'3,897 pass yds, 28 TD'),
    ('Russell Wilson','QB','NYG',14,'2,482 pass yds, 16 TD'),
    ('Brandon Aubrey','K','DAL',10,'34/39 FG, 5 from 50+'),
    ('Cameron Dicker','K','LAC',12,'39/42 FG'),
    ('Chris Boswell','K','PIT',5,'41/44 FG'),
    ('Jake Bates','K','DET',8,'27/32 FG'),
    ('Ka''imi Fairbairn','K','HOU',6,'30/34 FG'),
    ('Harrison Butker','K','KC',6,'23/26 FG'),
    ('Tyler Bass','K','BUF',7,'22/27 FG'),
    ('Jason Sanders','K','MIA',12,'28/32 FG'),
    ('Wil Lutz','K','DEN',12,'31/37 FG'),
    ('Younghoe Koo','K','ATL',5,'22/27 FG'),
    ('Denver Broncos','DST','DEN',12,'63 sacks, 18 takeaways'),
    ('Philadelphia Eagles','DST','PHI',9,'league-best pass defense'),
    ('Baltimore Ravens','DST','BAL',7,'54 sacks'),
    ('Minnesota Vikings','DST','MIN',6,'33 takeaways'),
    ('Buffalo Bills','DST','BUF',7,'32 takeaways'),
    ('Pittsburgh Steelers','DST','PIT',5,'40 sacks, 17 INT'),
    ('Houston Texans','DST','HOU',6,'49 sacks'),
    ('Green Bay Packers','DST','GB',5,'31 takeaways'),
    ('Detroit Lions','DST','DET',8,'top-10 scoring defense'),
    ('Seattle Seahawks','DST','SEA',8,'45 sacks')
  ) AS v(name,pos,team,bye,stat)
) t;